apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-tools
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: dev
            server: https://kubernetes.default.svc
  template:
    metadata:
      name: cluster-tools-{{name}}
    spec:
      project: default
      sources:
        # Source 1: Git repo that holds values files
        - repoURL: https://github.com/BBrucelee2002/gitops-k8-apps.git
          targetRevision: HEAD
          ref: values

        # Source 2: Argo CD Helm chart
        - repoURL: https://argoproj.github.io/argo-helm
          chart: argo-cd
          targetRevision: 8.0.9
          helm:
            valueFiles:
              - values/values/dev/argocd-values.yaml  # ✅ NO {{values}} here

        # Source 3: Cert Manager
        - repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: v1.17.2
          helm:
            valueFiles:
              - values/values/dev/cert-manager-values.yaml

        # Source 4: External Secrets
        - repoURL: https://charts.external-secrets.io
          chart: external-secrets
          targetRevision: v0.17.0
          helm:
            valueFiles:
              - values/values/dev/external-secrets-values.yaml

        # Source 5: Kubernetes Dashboard
        - repoURL: https://kubernetes.github.io/dashboard/
          chart: kubernetes-dashboard
          targetRevision: 7.12.0
          helm:
            valueFiles:
              - values/values/dev/dashboard-values.yaml

      destination:
        server: '{{server}}'
        namespace: cluster-tools

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
